# Generated by Django 5.2 on 2025-04-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('eth_address', models.CharField(max_length=42, unique=True)),
                ('role', models.CharField(choices=[('USER', 'User'), ('MODERATOR', 'Moderator')], default='USER', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/profile_pics')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
