# Generated by Django 5.2 on 2025-05-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Moderator')], default=1),
        ),
    ]
