# Generated by Django 5.2.1 on 2025-05-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_joined_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined_at',
            new_name='joined_date',
        ),
    ]
