# Generated by Django 5.2.1 on 2025-05-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_image'),
        ('dao', '0004_alter_dao_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_daos',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_users', to='dao.dao'),
        ),
    ]
