# Generated by Django 5.2.1 on 2025-05-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_favorite_daos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
