# Generated by Django 5.2.1 on 2025-05-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('progress', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('budget', models.BigIntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Planning'), (3, 'Completed'), (4, 'On Hold')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dao.dao')),
            ],
        ),
    ]
