# Generated by Django 5.2.1 on 2025-05-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('dao', '0003_alter_dao_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='dao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='dao.dao'),
        ),
    ]
