# Generated by Django 5.2.1 on 2025-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_alter_campaign_dao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
    ]
