# Generated by Django 5.2.1 on 2025-05-10 12:04

import django.core.validators
import submission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/dao_images', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png ']), submission.models.validate_image_size])),
                ('token', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
