# Generated by Django 5.2.1 on 2025-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dao',
            name='dao_cafe_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dao',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dao',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
