# Generated by Django 5.2.1 on 2025-05-11 16:51

import django.core.validators
import submission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0002_dao_dao_cafe_profile_dao_social_links_dao_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/dao_images', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png']), submission.models.validate_image_size]),
        ),
    ]
