# Generated by Django 5.2.1 on 2025-05-12 06:25

import django.core.validators
import submission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0003_alter_dao_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dao_images', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png']), submission.models.validate_image_size]),
        ),
    ]
