# Generated by Django 5.2.1 on 2025-05-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0004_alter_dao_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dao',
            old_name='dao_cafe_profile',
            new_name='create_dao_link',
        ),
    ]
