# Generated by Django 5.2.1 on 2025-05-14 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0005_rename_dao_cafe_profile_dao_create_dao_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dao',
            name='balance',
            field=models.DecimalField(decimal_places=18, max_digits=40, null=True),
        ),
        migrations.AddField(
            model_name='dao',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dao',
            name='network',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
