# Generated by Django 5.2.1 on 2025-05-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0006_dao_balance_dao_created_by_dao_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='dao',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
