# Generated by Django 5.2.1 on 2025-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0007_dao_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='network',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
