# Generated by Django 5.2.1 on 2025-05-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0008_alter_dao_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='network',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'ethereum'), (1, 'polygon'), (2, 'optimism'), (3, 'arbitrum'), (4, 'base'), (5, 'solana'), (6, 'near')], null=True),
        ),
    ]
