# Generated by Django 5.2.1 on 2025-05-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0009_alter_dao_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dao',
            name='create_dao_link',
        ),
        migrations.AddField(
            model_name='dao',
            name='create_dao',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
