# Generated by Django 5.2.1 on 2025-05-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0010_remove_dao_create_dao_link_dao_create_dao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dao',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
