# Generated by Django 5.2.1 on 2025-05-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0011_alter_dao_created_at_alter_dao_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dao',
            name='token',
        ),
    ]
