# Generated by Django 5.2 on 2025-05-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_reward_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='amount',
            new_name='reward',
        ),
    ]
