# Generated by Django 5.2 on 2025-05-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_rename_amount_reward_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='reward',
            new_name='rewards',
        ),
    ]
