# Generated by Django 5.2.1 on 2025-05-17 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_rename_reward_reward_rewards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='rewards',
            new_name='reward',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='date',
        ),
        migrations.AddField(
            model_name='reward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reward',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
