# Generated by Django 5.2.1 on 2025-05-17 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0005_rename_rewards_reward_reward_remove_reward_date_and_more'),
        ('submission', '0004_submission_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards', to='submission.submission'),
        ),
    ]
