# Generated by Django 5.2.1 on 2025-05-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_created_at_alter_task_reward_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]


# trigger actions
