# Generated by Django 5.2.1 on 2025-05-10 12:04

import django.core.validators
import django.db.models.deletion
import submission.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('proof_text', models.TextField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='media/proof_image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), submission.models.validate_image_size])),
                ('proof_video', models.FileField(blank=True, null=True, upload_to='media/proof_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov']), submission.models.validate_video_size])),
                ('proof_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Text'), (2, 'Image'), (3, 'Video')], null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='task.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
