# Generated by Django 5.2.1 on 2025-05-15 08:38

import django.core.validators
import submission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submission_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proof_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), submission.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='proof_video',
            field=models.FileField(blank=True, null=True, upload_to='proof_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov']), submission.models.validate_video_size]),
        ),
    ]
